### ISSUE TITLE
go的 sdk 无法 get 到本地

### ISSUE THREAD

**Issue by shuiche-it** [wxpusher/wxpusher-client#10]
go version 1.12.7

`> go get -u github.com/zjiecode/wxpusher-client  `
`> package github.com/zjiecode/wxpusher-client: no Go files in /Users/****/gopath/src/github.com/zjiecode/wxpusher-client
`

**Comment by TMaize** [comment]
用go mod试下

**Comment by xuange306** [comment]
> 用go mod试下

我已经解决了, 收到下载了 github 里的 zip 包, 迁移到 gopath 下,就可以用了

**Comment by zjiecode** [comment]
注意请求地址，go的放在了go文件夹里面。
另外go现在的sdk不是很完善，欢迎提PR来补充，感谢。😄
