### ISSUE TITLE
Android app 中版本使用

### ISSUE THREAD

**Issue by rangerzhou** [wxpusher/wxpusher-client#11]
### 1 Cleartext HTTP traffic not permitted
在 AndroidManifest.xml 中的 <application> 标签内添加 android:usesCleartextTraffic="true"

**Comment by zjiecode** [comment]
client是同步发送的，在Android需要使用子线程发送。

**Comment by zjiecode** [comment]
不推荐直接在android中调用wxpusher，应该调用你自己的服务器，你的服务器再调用wxpusher，避免appToken被泄漏
