### ISSUE TITLE
哈喽，提示文件内容超过2w字

### ISSUE THREAD

**Issue by liuyuexizhi** [wxpusher/wxpusher-client#17]
建议增加分条消息发送哦~！

**Comment by liuyuexizhi** [comment]
另外，可以增加发送图片的功能

**Comment by zjiecode** [comment]
最长发送2万，这个是没有问题的，如果有太长的内容，建议携带url，自己实现。
图片目前是支持的，直接发送html就可以了，只是图片的存储要自己实现。
