### ISSUE TITLE
请问如何发送一条这样的消息

### ISSUE THREAD

**Issue by panmingzhi815** [wxpusher/wxpusher-client#22]
https://s2.ax1x.com/2020/01/19/1Cwrt0.jpg

**Comment by zjiecode** [comment]
目前不支持这种格式。

**Comment by panmingzhi815** [comment]
请问这种格式的消息是怎么推送的？是消息模板吗，但我找了好久，没有有找到能显示图片的模板消息。

**Comment by TMaize** [comment]
> 请问这种格式的消息是怎么推送的？是消息模板吗，但我找了好久，没有有找到能显示图片的模板消息。

这个应该是描述比较长的图文消息
