### ISSUE TITLE
新版本可否保留标题字段,内信只展示标题而不展示内容

### ISSUE THREAD

**Issue by xiaoqidela** [wxpusher/wxpusher-client#26]
新版本的消息详情真的很棒,但markdown的消息内容被内信展示出来看的真的很乱,可否在内信只展示标题,查看原文再展示消息详情

**Comment by zjiecode** [comment]
这个后面可以考虑，下个版本应该会这样设计。

**Comment by xiaoqidela** [comment]
期待...

**Comment by zjiecode** [comment]
目前已经支持，可以传递一个新的字段，summary，表示消息摘要。欢迎体验。
