### ISSUE TITLE
扫码关注应用等情况下返回链接，由客户端生成二维码？

### ISSUE THREAD

**Issue by AlexGuo1998** [wxpusher/wxpusher-client#27]
关注时需要使用动态二维码，每次调用API返回一张图片。
能否考虑增加一个接口，直接返回二维码的文字内容（如`http://weixin.qq.com/q/xxxxxx`），或返回一个JSON，然后由客户端自己来生成二维码？

**Comment by zjiecode** [comment]
不建议这样做，其实是有方案的，返回二维码的token，但是二维码的token有一个有效时间，他会过期，直接给你token，你不太好管理有效时间，你直接用我给的链接访问二维码，我会管理有效时间，过期了会自动更新，保证给你的二维码图片是永久有效的。
