### ISSUE TITLE
markdown格式中的表格不能正确解析

### ISSUE THREAD

**Issue by ehznahz** [wxpusher/wxpusher-client#30]
markdown中的表格不能正确显示（此表格在typora中可以正常显示，python的markdown也能正确解析），分隔符还是显示成“｜”。

**Comment by zjiecode** [comment]
检查传的contentType是不是3？

**Comment by ehznahz** [comment]
字段`contentType`设置的确实是`3`，除了表格之外标题、链接、图片均可正常解析。
