### ISSUE TITLE
服务器通过node.js 调用报错

### ISSUE THREAD

**Issue by LeeYouRan** [wxpusher/wxpusher-client#34]
{ Error: getaddrinfo ENOTFOUND wxpusher.zjiecode.com wxpusher.zjiecode.com:80
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'wxpusher.zjiecode.com',
  host: 'wxpusher.zjiecode.com',
  port: 80 }

**Comment by zjiecode** [comment]
需要给出具体的错误信息，通过这个看不出来是哪儿错了

**Comment by fzq19900228** [comment]
解决了吗

**Comment by zjiecode** [comment]
> 解决了吗

目前服务是没有问题的，这个应该是他调用的问题。
