### ISSUE TITLE
请问消息到达后能否发出提醒？

### ISSUE THREAD

**Issue by AllenMeex** [wxpusher/wxpusher-client#38]
我试了一下，好像消息是没有提示的

**Comment by zjiecode** [comment]
发出提醒是啥意思，微信自己是有提醒的，你可以检查你的微信设置。

**Comment by AllenMeex** [comment]
就是当微信不在前台时，我用demo发了个消息，消息不会在通知栏里提醒，只有打开微信才能看到这条消息

**Comment by zjiecode** [comment]
这个是微信的消息提醒设置，是支持的，建议检查一下自己的微信消息设置。



---原始邮件---
发件人: "M.Lawliet"<notifications@github.com&gt;
发送时间: 2021年1月5日(周二) 上午9:47
收件人: "wxpusher/wxpusher-client"<wxpusher-client@noreply.github.com&gt;;
抄送: "zjiecode"<zjiecode@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [wxpusher/wxpusher-client] 请问消息到达后能否发出提醒？ (#38)




 
就是当微信不在前台时，我用demo发了个消息，消息不会在通知栏里提醒，只有打开微信才能看到这条消息

**Comment by AllenMeex** [comment]
检查了下，确实是设置问题。。
很好的项目~
