### ISSUE TITLE
中文乱码

### ISSUE THREAD

**Issue by skywolf627** [wxpusher/wxpusher-client#7]
用C#发送post请求，内容不转urlEncode，发送失败。
如果转urlEncode，发送成功，但是微信收到的内容就是 urlEncode 之后的内容，并没有变成文字。
%e9%a2%84%e4%bc%b0%e6%80  类似这样
 `     var data = new
                {
                    appToken = "AT_Fd******",
                    content = HttpUtility.UrlEncode("中文"),
                    contentType = 1,
                    uids = new string[] { "UID_******" }
                };`

调用你页面上面的GET请求，同样的urlEncode，发送成功后，微信显示正常。

**Comment by TMaize** [comment]
urlEncode是get请求使用的，你可以搜索下C# POST 中文乱码

**Comment by skywolf627** [comment]
> urlEncode是get请求使用的，你可以搜索下C# POST 中文乱码

POST 如果没有urlEncode， 接口这边返回的是

{"code":1005,"msg":"接口 [/api/send/message] 出现异常：JSON parse error: Invalid UTF-8 start byte 0xb9; nested exception is com.fasterxml.jackson.databind.JsonMappingException: Invalid UTF-8 start byte 0xb9\n at [Source: (PushbackInputStream); line: 1, column: 61] (through reference chain: com.zjiecode.wxpusher.server.biz.bean.SendMessageReq[\"content\"])","data":null,"success":false}

参数我也序列化成json了
{"appToken":"AT_xxx","content":"xxxx6\r\n\r\nxxx\r\nxxxx\r\n\r\n","contentType":1,"uids":["UID_xxxx"]}

**Comment by TMaize** [comment]
post请求头contentType设置为application/json试试

**Comment by zjiecode** [comment]
- post请求，内容不需要urlEncode，get请求才需要
- 不转post请求失败，可以贴一下请求错误是啥，方便排查，另外，你可以检查楼上说的：contentType还有请求的body是不是标准的json格式
- GET请求，内容是需要urlEncode的，避免乱码

有问题，欢迎再即使反馈。

**Comment by hupo376787** [comment]
```
            var json = new WxPusherModel()
            {
                appToken = "AT_xxxxxxxxxxxxx",
                content = HttpUtility.UrlEncode("测试WxPusher"),
                contentType = 1,
                topicIds = new int[] { 150},
                uids = new string[] { "UID_xxxxxxxxxxxxxxxxxx" },
            };
            HttpContent content = new StringContent(json.ToString(), Encoding.UTF8, "application/json");
            var response2 = await httpClient.PostAsync("http://wxpusher.zjiecode.com/api/send/message", content);
            Console.WriteLine("WxPusher发送状态：" + response2.StatusCode);
```

你好，这样发送200成功，但是微信没有收到消息，是则么回事，谢谢

**Comment by zjiecode** [comment]
> ```
>             var json = new WxPusherModel()
>             {
>                 appToken = "AT_xxxxxxxxxxxxx",
>                 content = HttpUtility.UrlEncode("测试WxPusher"),
>                 contentType = 1,
>                 topicIds = new int[] { 150},
>                 uids = new string[] { "UID_xxxxxxxxxxxxxxxxxx" },
>             };
>             HttpContent content = new StringContent(json.ToString(), Encoding.UTF8, "application/json");
>             var response2 = await httpClient.PostAsync("http://wxpusher.zjiecode.com/api/send/message", content);
>             Console.WriteLine("WxPusher发送状态：" + response2.StatusCode);
> ```
> 
> 你好，这样发送200成功，但是微信没有收到消息，是则么回事，谢谢

发送后，返回是啥，是否有异常，请给出messageID。

**Comment by hupo376787** [comment]
@zjiecode 现在好了。原来还要关注一下应用，另外我json序列化的也有问题，谢谢
