### ISSUE TITLE
MessageId=589793,获取消息状态是已经发送成功，但是用户没有收到

### ISSUE THREAD

**Issue by HalfWater** [wxpusher/wxpusher-client#9]
如题

http://wxpusher.zjiecode.com/api/send/query/589793
{
    "code": 1000,
    "msg": "发送成功",
    "data": 3,
    "success": true
}

**Comment by zjiecode** [comment]
已经发现类似问题，排查以后发现，我这边是正常发送给微信，并且，微信服务器是正常返回的。

观察规律，感觉是短时间内给这个用户的发送并发太高了造成的，建议控制一下发送频率，短时间发送消息的话，做一下数据聚合再发送。
